### ISSUE TITLE
docker-machine-unison require a password for ssh 

### ISSUE THREAD

**Issue by krivochenko** [fmasa/docker-machine-unison#3]
I followed Readme of this repo. When I run provision.sh, it use for ssh-connection my host-machine user (not docker) and ask me a password:
```
$ /c/docker-machine-unison/provision.sh
(default) Checking whether /c/Users (vboxsf) is mounted ...
(default) Creating /c/Users ...
(default) Checking whether unison is installed ...
(default) Installing unison ...
Setting up unison ...
Done!
sergey@192.168.99.100's password:
```

Thanks in advance!

**Comment by fmasa** [comment]
Can you try running /provision.sh on freshly created docker machine?

**Comment by krivochenko** [comment]
1. I droped existing VM `default`. Also I remove string with IP 192.168.99.100 from ~/.ssh/khown_hosts file.
2. I run Docker Quickstart Terminal wich finished with expected result - new VM was created.
3. I run new Git Bash terminal and executed:
- cd /c/docker-machine-unison
- /c/docker-machine-unison/provision.sh

```
(default) Checking whether /c/Users (vboxsf) is mounted ...
(default) Creating /c/www ...
(default) Checking whether unison is installed ...
(default) Installing unison ...
Setting up unison ...
Done!
The authenticity of host '192.168.99.100 (192.168.99.100)' can't be established.
ECDSA key fingerprint is SHA256:W2/IHAVVEHc1GHb4s7w3kY9PPv4kzyWcIK6u2Fnt31Q.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.99.100' (ECDSA) to the list of known hosts.
sergey@192.168.99.100's password:
Permission denied, please try again.
sergey@192.168.99.100's password:
Permission denied, please try again.
sergey@192.168.99.100's password:
Permission denied (publickey,password,keyboard-interactive).
Fatal error: Lost connection with the server
```

When I connect to the VW, I can see /c/www folder, but it's empty.

My config.conf:
```
DOCKER_MACHINE: default
UNISON_PROFILE_NAME: docker
UNISON_FASTCHECK: false
HOST_FOLDER: C:/www
GUEST_FOLDER: /c/www
IGNORE: {.git,.idea}
```

**Comment by krivochenko** [comment]
Any ideas? Which additional information can I provide?

**Comment by luckydonald** [comment]
> 3. I run new Git Bash terminal and executed

But you run the `eval (docker-machine env default)` step?

Does it work in the Docker Quickstart Terminal?

**Comment by luckydonald** [comment]
Also check `$(pwd)/.docker-config/ssh-config`.
It should look like:
```
Host 192.168.0.123
    User docker
    UdentityFile ~/.docker/machine/machines/default/id_rsa
```
In my case after the host there was nothing.

**Comment by krivochenko** [comment]
The problem was in `ssh-config`. IP adress was missed. I solved it in my fork. Thanks for help.

**Comment by fmasa** [comment]
@krivochenko You can send PR if you have a fix 🙂
